bscSignUrl = "http://127.0.0.1:8585"
bscSignUser = ""
bscSignPassword = ""

[transaction]
fromAddress = "0x3cb0bdcbdeb23896ee914afbfa45842d43791823"
amount = "5900000"
fee = 0
toAddrFileName = "toAddress.csv"
contractAddress = "0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56"
